package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST, LOGIN_OUTCOME,
    NEW_GAME_REQUEST,
    LOBBY,
    GAME_START,
    ERROR,
    FILL_CLOUD_CARDS,
    PLAY_ASSISTANT_CARD,
    MOVE_STUDENT_TO_ISLAND,
    MOVE_STUDENT_TO_DINING_ROOM,
    MOVE_MOTHER_NATURE,
    CHOOSE_CLOUD_CARD,
    END_PLAYER_TURN,
    CC_ALL_REMOVE_COLOR,
    CC_BLOCK_COLOR_ONCE,
    CC_CHOOSE_1_DINING_ROOM,
    CC_BLOCK_TOWER,
    CC_CHOOSE_3_TO_ENTRANCE,
    CC_CHOOSE_ISLAND,
    CC_CHOOSE_1_TO_ISLAND,
    CC_EXCHANGE_2_STUDENTS,
    CC_NO_ENTRY_ISLAND,
    CC_PLUS_2_INFLUENCE,
    CC_TEMP_CONTROL_PROF,
    CC_TWO_ADDITIONAL_MOVES
}
