package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST, LOGIN_OUTCOME,
    NEW_GAME_REQUEST,
    CHOOSE_WIZARD, WIZARDS_UPDATE, WIZARD_ERROR,
    LOBBY,
    FILL_CLOUD_CARDS,
    ASK_ASSISTANT_CARD, PLAY_ASSISTANT_CARD,
    ASSISTANT_CARD_PLAYED,
    UPDATE,
    ASK_ACTION_PHASE_1,
    MOVE_STUDENT_TO_ISLAND,
    MOVE_STUDENT_TO_DINING_ROOM,
    ASK_ACTION_PHASE_2,
    MOVE_MOTHER_NATURE,
    ASK_ACTION_PHASE_3,
    CHOOSE_CLOUD_CARD,
    END_PLAYER_TURN,

    PLAY_CHARACTER_CARD,
    ASK_CC_ALL_REMOVE_COLOR_INPUT, CC_ALL_REMOVE_COLOR_REPLY,
    ASK_CC_BLOCK_COLOR_ONCE_INPUT, CC_BLOCK_COLOR_ONCE_REPLY,
    ASK_CC_CHOOSE_1_DINING_ROOM_INPUT, CC_CHOOSE_1_DINING_ROOM_REPLY,
    ASK_CC_CHOOSE_1_TO_ISLAND_INPUT, CC_CHOOSE_1_TO_ISLAND_REPLY,
    ASK_CC_CHOOSE_3_TO_ENTRANCE_INPUT, CC_CHOOSE_3_TO_ENTRANCE_REPLY, CC_CHOOSE_3_TO_ENTRANCE_PARTIAL_REPLY, CC_CHOOSE_3_TO_ENTRANCE_STOP,
    ASK_CC_CHOOSE_ISLAND_INPUT, CC_CHOOSE_ISLAND_REPLY,
    ASK_CC_EXCHANGE_2_STUDENTS_INPUT, CC_EXCHANGE_2_STUDENTS_REPLY, CC_EXCHANGE_2_STUDENTS_PARTIAL_REPLY, CC_EXCHANGE_2_STUDENTS_STOP,
    ASK_CC_NO_ENTRY_ISLAND_INPUT, CC_NO_ENTRY_ISLAND_REPLY,

    STRING_MESSAGE,
    PING,
    SHUTDOWN_CLIENT,
    SERVER_UNREACHABLE,
    WINNER_TO_OTHERS, WINNER
}
